repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest
        entry: python -m pytest
        language: system
        types: [python]
        stages: [pre-push]
        pass_filenames: false
        args: [ "--confcutdir=.", "tests" ]
