[tool.poetry]
name = "linkedin-bot"
version = "0.1.0"
description = ""
authors = ["fenya-rq <fenyochek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.13.3"
ruff = "0.11.5"
pytest = "8.3.5"
mypy = "1.15.0"
beautifulsoup4 = "4.13.3"
playwright = "1.51.0"
httpx = "0.28.1"
python-dotenv = "1.1.0"
asyncio = "3.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
