name: LinkedIn Bot CI

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.5'

    - name: Install Poetry
      run: pip install poetry

    - name: Configure Poetry for in-project virtualenv
      run: poetry config virtualenvs.in-project true

    - name: Cache Poetry virtualenv
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: ${{ runner.os }}-poetry-py-3.13.5-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-py-3.13.5-
          ${{ runner.os }}-poetry-py-
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Check code with Ruff
      run: poetry run ruff check

    - name: Format code with Ruff
      run: |
        poetry run ruff format

    - name: Run tests
      run: poetry run pytest
